### PR TITLE
allowing to specify sender

### PR DESCRIPTION
**Pull request by myownsumm**
GAE is allowing to specify custom email senders listed in project settings.

### CODE REVIEW

**Comment by myownsumm** [comment]
@shpasser are there any problems with the code to accept the pull request?

**Comment by shpasser** [comment]
Yep, the documentation has to be updated accordingly, and even then will have to test the change and choose the right approach to incorporate it.

**Comment by shpasser** [comment]
Additionally `$message->getSender()` returns a string according to Swift Mailer documentation.

**Comment by myownsumm** [comment]
@shpasser but in fact it is an array.

**Comment by shpasser** [comment]
Indeed you are correct. Please notice that `sender` field has to be defined when the message contains more than one address in its `from` field, meaning the `sender` field is not mandatory. As you can see it is very important to explore the possible uses of the feature and test it before I will be able to accept the pull request. Please do not forget to update the `readme` file.

**Comment by shpasser** [comment]
@myownsumm are you in?

**Comment by shpasser** [comment]
Hi @myownsumm, I'm going to wait for 3 more days for your decision. If I do not have your answer by then I'll have to decide if I'm going to implement the feature or close the request.

**Pull request closed without merging**
